apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: PostgresUsers
    type: postgres
    access: proxy
    url: db:5432
    database: leetdb
    user: leet
    secureJsonData:
      password: leetpass

  - name: Timescale
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: news_bets_db
    user: timescale_user
    secureJsonData:
      password: timescale_pass
